name: Install TikTok Base Code

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger

jobs:
  install-tiktok-base:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install TikTok Base Code in HTML files
        run: |
          # Define the exact TikTok base code
          TIKTOK_BASE_CODE='<!-- TikTok Pixel Code Start -->
          <script>
          !function (w, d, t) {
            w.TiktokAnalyticsObject=t;var ttq=w[t]=w[t]||[];ttq.methods=["page","track","identify","instances","debug","on","off","once","ready","alias","group","enableCookie","disableCookie","holdConsent","revokeConsent","grantConsent"],ttq.setAndDefer=function(t,e){t[e]=function(){t.push([e].concat(Array.prototype.slice.call(arguments,0)))}};for(var i=0;i<ttq.methods.length;i++)ttq.setAndDefer(ttq,ttq.methods[i]);ttq.instance=function(t){for(var e=ttq._i[t]||[],n=0;n<ttq.methods.length;n++)ttq.setAndDefer(e,ttq.methods[n]);return e},ttq.load=function(e,n){var r="https://analytics.tiktok.com/i18n/pixel/events.js",o=n&&n.partner;ttq._i=ttq._i||{},ttq._i[e]=[],ttq._i[e]._u=r,ttq._t=ttq._t||{},ttq._t[e]=+new Date,ttq._o=ttq._o||{},ttq._o[e]=n||{};n=document.createElement("script");n.type="text/javascript",n.async=!0,n.src=r+"?sdkid="+e+"&lib="+t;e=document.getElementsByTagName("script")[0];e.parentNode.insertBefore(n,e)};
            ttq.load("D2G8HPBC77U9U4KDPBTG");
            ttq.page();
          }(window, document, "ttq");
          </script>
          <!-- TikTok Pixel Code End -->'
          
          # Counter for modified files
          modified_count=0
          
          # Process all HTML files
          find . -name "*.html" -type f | while read -r file; do
            echo "Processing: $file"
            
            # Check if TikTok pixel already exists
            if grep -q "TikTok Pixel Code Start" "$file"; then
              echo "  → TikTok pixel already exists, skipping"
            else
              # Check if file has a <head> section
              if grep -q "<head>" "$file"; then
                # Insert the base code right after <head>
                awk -v code="$TIKTOK_BASE_CODE" '
                  /<head>/ { print; print code; next }
                  { print }
                ' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
                
                echo "  ✓ Added TikTok base code to $file"
                modified_count=$((modified_count + 1))
              else
                echo "  ⚠ No <head> tag found in $file, skipping"
              fi
            fi
          done
          
          echo "Modified $modified_count HTML files"
          
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Install TikTok base code on HTML pages"
            git push
            echo "✓ Changes pushed to repository"
          fi
